### PR TITLE
Enable warnings

### PR DESCRIPTION
**Pull request by audrow**

### CODE REVIEW

**Review by clalancette — APPROVED** [review]
Looks good with green CI.  Surprised that no code changes were necessary :).

**Comment by audrow** [comment]
I had to rebase because I didn't have the most recent version. I had to remove a `std::move` from a return statement.

Here's CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12458/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7425/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10169/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12377/)

**Comment by clalancette** [comment]
@sloretz Could you take a look?  This is in the new code from #13

**Comment by audrow** [comment]
[Here](https://stackoverflow.com/a/62061731/3335057) is a StackOverflow post on move in return statements.

**Review by sloretz — APPROVED** [review]

**Pull request merged**
