### PR TITLE
Include cmake file before using

### PR DESCRIPTION
**Pull request by homalozoa**
add a include before using command 'pluginlib_enable_plugin_testing'.

### CODE REVIEW

**Comment by clalancette** [comment]
Can you please explain a little more about why this is needed?  From my testing, the tests seem to work without this, but maybe there is some combination I'm missing.

**Comment by homalozoa** [comment]
Hi, there was a "command not found" error occured when I was compiling urdf.  It returned can not find command "pluginlib_enable_plugin_testing".  So I add this declaration to tell CMake where to find this command. The CMake version is 3.20.1, I'm using Arch Linux.

**Comment by sloretz** [comment]
This should definitely not be needed.

`pluginlib` [includes an extra file](https://github.com/ros/pluginlib/blob/7cfba769e963ad9b3e75b8d9068913fc8e5086bd/pluginlib/CMakeLists.txt#L105) when [one calls `find_package(pluginlib)`](https://github.com/ament/ament_cmake/blob/84719051ef2b26070de484e60b8f060ae7a70b06/ament_cmake_core/cmake/core/ament_package.cmake#L24-L31). That file [includes `pluginlib_enable_plugin_testing.cmake`](https://github.com/ros/pluginlib/blob/7cfba769e963ad9b3e75b8d9068913fc8e5086bd/pluginlib/pluginlib-extras.cmake#L22). 

 If this isn't working then there's definitely a bug that should be fixed elsewhere. Would you mind providing a reproducible example, like a Dockerfile or a series of commands to run on a fresh arch install, that can reproduce the error?

**Comment by homalozoa** [comment]
My mistake. The FOXY cache made this mistake. I'll close this PR.

**Pull request closed without merging**
