### PR TITLE
Added commom linters

### PR DESCRIPTION
**Pull request by ahcorde**

### CODE REVIEW

**Review by clalancette — APPROVED** [review]
Looks good to me with green CI.

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21697/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15972/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1199/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22402/)

Included https://github.com/ros2/rviz/pull/1266

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21710/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15984/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1216/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22414/)

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21712/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15988/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1218/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22417/)

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21713/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15990/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1220/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22418/)

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21717/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15992/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1222/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22420/)

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21732/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16007/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1238/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22435/)

**Comment by sea-bass** [comment]
FYI this PR seems to have broken some MoveIt tests that still import `urdf/model.h` because this linting PR also snuck in a compiler warning that MoveIt's CI treats as error.

See e.g. https://github.com/moveit/moveit2/pull/3003 and https://github.com/moveit/srdfdom/pull/127

I don't think any action is needed from here, but just informing that the MoveIt maintainer team will need to update `srdfdom` and `moveit2` to deal with this going forward, as discussed in the 2 PRs above.

**Pull request merged**
