### PR TITLE
Add dependency on TinyXML2

### PR DESCRIPTION
**Pull request by sloretz**
Fixes undeclared dependency bug in #13

### CODE REVIEW

**Review by clalancette — APPROVED** [review]
Looks good with green CI.  This will conflict with #17 , but I'm assuming @sloretz will sort it out.

**Comment by sloretz** [comment]
Rebased to fix merge conflict - should be no changes, but I'll ask for another review in case I'm missing something

**Comment by sloretz** [comment]
CI (build: `--packages-above-and-dependencies urdf` test: `--packages-above urdf`)
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12370/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7339/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10082/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12282/)

**Review by clalancette — APPROVED** [review]
Looks good with green CI.

**Comment by sloretz** [comment]
Rerun of CI since failures were unrelated to this PR
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12408/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7375/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10118/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12321/)

**Comment by sloretz** [comment]
Approved and CI LGTM, merging :tada:

**Pull request merged**
